### PR TITLE
Feature: ERC721 badge contract

### PR DESCRIPTION
**Pull request by george-openformat**
## Summary

- [x] Added ERC721 Badge contract
- [x] Tests for ERC721 Badge contract
- [x] Added `createERC721WithTokenURI` to `ERC721FactoryFacet`
- [x] integration tests
- [x] deployment scripts
- [x] updated CreateApp script to make deployer the owner

I will create a new issue for these as this is urgent
- [ ] gas costs
- [ ] docs

### ERC721Badge contact
The implementation consists of adding `ERC721Badge` contract which is near identical to the `ERC721LazyMint` contract. 
The main differences:
- expects `baseURIForTokens` to be encoded in the `data` parameter for `initialize`
- lazy mints all tokens with that `baseURIForTokens` on `initialize`
- allows owner to update the baseURIForTokens with the function `setBaseURI`
- remove the `lazyMint` function

### ERC721FactoryFacet
As the ERC721Badge contract requires a tokenURI on initialize I have added a new function to the contract
`createERC721WithTokenURI`. This is so the `createERC721` function can still be used as is.

However `createERC721WithTokenURI` can be used to create base and lazyMint implementations by setting the tokenURI to an empty string [see this test](https://github.com/open-format/contracts/blob/cfe2e5570e9f0a6cb4b10c63efaab49db548ce14/test/integration/facet/ERC721FactoryFacet.t.sol#L289-L304)

### Deployment scripts
current deployments should be updated with
```
make update-ERC721Badge rpc="<chain name>"
```
this will update the ERC721FactoryFacet by adding `createERC721WithTokenURI` and replace all other functions.
and then it will deploy the ERC721Badge contract and add it as an ERC721 implementation under the id `"Badge"`

## Related Issue/Bounty
issue [OF-57](https://linear.app/openformat/issue/OF-57/feature-erc721-badge-contract)

## Type of Change

Please check the boxes that apply to your pull request:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (changes to documentation only)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Testing

To run tests `forge test`

I have manually tested the update script with the following steps:

1. `git checkout main`
2. run `anvil`
3. in a new terminal `make deploy rpc="anvil"`
4. `git checkout `git checkout feature/ERC721-badge-contract`
5. `make CreateApp` and saving the dpeloyed address to APP_ID in .env
6. `make createERC721Base` will run successfully
7. `make createERC721Badge` will revert (as it doesn't exist on the app)
8. `make update-ERC721Badge` to deploy updated contracts
9. `make createERC721Badge` will successfully create a new ERC721Badge contract

video example:
[Screencast from 14-05-24 16:37:26.webm](https://github.com/open-format/contracts/assets/167979344/dfe964be-c24a-4197-bf4b-ade75d029625)

## Checklist

- [x] I have read the [CONTRIBUTING.md](CONTRIBUTING.md) document
- [x] I have followed the project's [style guide](CONTRIBUTING.md#style-guide)
- [x] I have added or updated tests to cover my changes
- [x] All new and existing tests passed
- [x] My changes generate no new warnings or errors
- [x] I have made corresponding changes to the documentation
- [x] I have checked that my changes do not introduce any new security vulnerabilities
- [x] I have provided a clear and concise description of my changes
- [x] I have linked to the related issue or bounty, if applicable

## Additional Information

---

Once again, thank you for your contribution! We appreciate your effort and dedication to improving the Open Format.

### CODE REVIEW

**Comment by george-openformat** [comment]
hey @tinypell3ts apologies for the delay with this. I have run into an issue that the deployment script will result in a breaking changes as the `createERC721` function now requires and extra parameter `baseTokenURI`. 

I want to explore a more stepped approach taking advantage of function overrides. leaving the old function on the diamond contract and adding the new one. but this is untested and not something I have time to go into right now.  Do you think this is worth looking at monday?

**Comment by tinypell3ts** [comment]
> hey @tinypell3ts apologies for the delay with this. I have run into an issue that the deployment script will result in a breaking changes as the `createERC721` function now requires and extra parameter `baseTokenURI`.
> 
> I want to explore a more stepped approach taking advantage of function overrides. leaving the old function on the diamond contract and adding the new one. but this is untested and not something I have time to go into right now. Do you think this is worth looking at monday?

Hey @george-openformat - thanks for this. Let's pick this up Monday.

**Comment by george-openformat** [comment]
After consideration I have opted for adding a function to the factory facet, `createERC721WithTokenURI` and keep `createERC721` as is. By adding a function instead of replacing we don't break any existing functionality and can smoothly add it in at all levels (subgraph, api, sdk)

commits to follow shortly.

**Review by tinypell3ts — APPROVED** [review]
Welcome back. This is awesome 🎉🎉🎉

**Review by nup9151f — APPROVED** [review]

**Pull request merged**
